[project]

site_name = "Adenyrr's docu"

site_description = "mkdir /dev/docs"

site_author = "adenyrr"

site_url = "https://docu.adenyrr.me"

copyright = """
Creative Commons BY - NC : adenyrr
"""

repo_url = "https://github.com/adenyrr/docu"
repo_name = "adenyrr/docu"

nav = [
   
  {"/root" = "https://adenyrr.me"},
  {"/home" = [
     {"/à-propos" = "index.md"},
  ]},
  {"/network" = [
     {"/swag-proxy" = "reseau/swag.md"},
  ]},
  {"/apps" = [
     {"/jellyfin" = [
      {"/install" = "services/jellyfin/install.md"},
      {"/theme" = "services/jellyfin/theme.md"},
     ]},
     {"/ollama" = [
      {"/install" = "services/ollama/install.md"},
      {"/config" = "services/ollama/config.md"},
     ]},
  ]},
  {"/assist" = [
     {"/install" = "hassio/install.md"},
     {"/météo" = "hassio/meteo.md"},
  ]},
  {"/tools" = [
     {"/more" = "outils/ressources.md"},
     {"/cmd" = "outils/commandes.md"},
     {"/discover" = "outils/softwares.md"},
     {"/links" = "outils/links.md"},
  ]},
  {"/non-free" = [
     {"Sysprep Windows" = "non-oss/sysprep.md"},
   ]}
]

#extra_css = ["assets/stylesheets/extra.css"]
#extra_javascript = ["assets/javascript/extra.js"]

site_dir = "public"

[project.theme]

variant = "modern"
custom_dir = "overrides"
favicon = "assets/favicon.jpg"
logo = "assets/favicon.jpg"

language = "fr"

features = [
    "announce.dismiss",
    "content.action.view",
    "content.code.annotate",
    "content.code.copy",
    "content.code.select",
    "content.footnote.tooltips",
    "content.tabs.link",
    "content.tooltips",
    "header.autohide",
    "navigation.footer",
    "navigation.indexes",
    "navigation.instant",
    "navigation.instant.prefetch",
    "navigation.instant.progress",
    "navigation.path",
    "navigation.sections",
    "navigation.tabs",
    "navigation.tabs.sticky",
    "navigation.top",
    "navigation.tracking",
    "search.highlight",
    "toc.follow",
    "navigation.indexes"

]

# Palette toggle for light mode

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

# Palette toggle for dark mode

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

[project.theme.font]
text = "Inclusive Sans"
code = "Jetbrains Mono"

[project.theme.icon]
repo = "fontawesome/brands/github"

[project.extra]

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/adenyrr"


[[project.extra.social]]
icon = "fontawesome/brands/gitlab"
link = "https://gitlab.com/adenyrr"


[[project.extra.social]]
icon = "fontawesome/brands/discord"
link = "https://https://discord.com/invite/6PrX5KM4MH"

[project.markdown_extensions]
abbr = {}
admonition = {}
attr_list = {}
footnotes = {}
md_in_html = {}
"mkdocs-click" = {}

[project.markdown_extensions.pymdownx]
critic = {}
details = {}
keys = {}
snippets = {}
inlinehilite = {}

[project.markdown_extensions.pymdownx.arithmatex]
generic = true

[project.markdown_extensions.pymdownx.highlight]
anchor_linenums = true
line_spans = "__span"
pygments_lang_class = true

[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true

[project.markdown_extensions.toc]
permalink = true
title = "On this page"
permalink_title = "Anchor link to this section for reference"

[project.markdown_extensions.pymdownx.superfences]
custom_fences = [
    { name = "mermaid", class = "mermaid", format = "pymdownx.superfences.fence_code_format" },
]


[project.plugins]

[project.plugins.offline]
enabled = true

[project.plugins.glightbox]

[project.plugins.search]


